### ISSUE TITLE
Error when run yarn start:ui on Chrome - TypeError: Accessor not expected at intrinsics.%IteratorPrototype%.constructor at installSesLockdown.ts:7:1

### ISSUE THREAD

**Issue by rider-cantuaria-eng** [Agoric/dapp-offer-up#87]
Hello guys, I got this error* `TypeError: Accessor not expected at intrinsics.%IteratorPrototype%.constructor
  at installSesLockdown.ts:7:1` when I'm using the Chrome** browser. **In Firefox, it works fine.**

1. SO: Ubuntu 23.04
2. Chrome Version:  Version 125.0.6422.60 (Official Build) (64-bit)

[*]
![image](https://github.com/Agoric/dapp-offer-up/assets/96726225/23a5e1e9-6411-4789-8f30-fc817606d3a5)
[**]
![image](https://github.com/Agoric/dapp-offer-up/assets/96726225/82d0b05d-4ac0-4726-b7e5-30b4c6597484)

**Comment by dckc** [comment]
Hi. Thanks for sharing you're experience.

Several of us are pretty surprised by those symptoms. They suggest an odd version of `ses` is involved somehow. It should be 1.3.0:

https://github.com/Agoric/dapp-offer-up/blob/b4731f439f8174bb0145e74883096d2e602dbdf7/package.json#L13


 What does `yarn why ses` show?

Stepping back a bit... what happened just before these symptoms? Were you following the [getting started tutorial](https://docs.agoric.com/guides/getting-started/)? You got as far as `yarn start:ui`? Then when you opened your browser, you immediately saw these errors?

**Comment by samsiegart** [comment]
For reference, this is my chrome version:

![image](https://github.com/Agoric/dapp-offer-up/assets/8848650/3bd3bc44-b291-4c5c-874a-99d9b5cba2b9)

And `yarn why ses`:

```
=> Found "ses@1.3.0"
info Reasons this module exists
   - "_project_#offer-up-ui" depends on it
   - Hoisted from "_project_#offer-up-ui#ses"
   - Hoisted from "_project_#@agoric#swingset-vat#@endo#compartment-mapper#ses"
   - Hoisted from "_project_#@agoric#casting#@endo#lockdown#ses"
   - Hoisted from "_project_#@agoric#xsnap#@endo#netstring#ses"
   - Hoisted from "_project_#@agoric#notifier#@endo#promise-kit#ses"
   - Hoisted from "_project_#offer-up-contract#@endo#ses-ava#ses"
   - Hoisted from "_project_#@agoric#xsnap#@endo#stream-node#ses"
   - Hoisted from "_project_#@agoric#xsnap#@endo#stream#ses"
   - Hoisted from "_project_#@agoric#swingset-vat#@endo#compartment-mapper#@endo#static-module-record#ses"
info Disk size without dependencies: "3.27MB"
info Disk size with unique dependencies: "3.33MB"
info Disk size with transitive dependencies: "3.33MB"
info Number of shared dependencies: 1
Done in 0.42s.
```
I don't see such an error when I start the dapp from fresh clone of the repo.
